# Generated by Django 4.2.11 on 2026-05-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_adminprofile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
